sudo: false
language: node_js
node_js:
  - 8
  - 6
  - 4
script: npm test
branches:
  only:
    - master
    - /^v[0-9]/
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: vy1OpQLorMT/ZNdDO1gME7UXRuBaHYhSL1MiDPGI52U7yS3LEZ73XbFtptyPtPIzzwOx1nBE64IlcGhAjZop76GhKy7p6Bg5jJfZ+Ga3DE4XeSeBJ9iFFHq+PeILTqSRpGJRSeM2bGTL67OGWi+qfaDEIpPD9NcAXymETpNue4ns7ZJfsxY8N46EkYa5epMc/VldpPKP9Gqs2Z8WFPTFNHEqMC7CM6If0Hd/XqT4zEXjpBA5L8nzGX0m9eLecYgA8jIhqkyW3FkJt1WjwEE5Q8uoIe1siqKeJKzrf0889yDndfiLyr4sdgGOW8T8Z+bSHezN3ijj4cjvPS265icK2Uy3cy2T7/jPim23yNTAicpwJJMChagkbNlcEdn3mnNGSPs90QeKtPL3t/jJsQz0TuCUjGfBL+0vrk+mI4JhombbMwf806sUzTWyWCrMryEKCYOZX1MADNA9wnAotNRhOqfrDMMD1nOw+qS+06ypW3S52FKA2SnO2WjqjzQELdXqb+Qud0yqxOfXWC9ub2WF6dvc8wcdn7hKPVYg2EUhg6FhJa0Awzy3PwDuVHcXdI26nsBzB+OkExogyNkfi2zY9FzLoa8CJjHk8soBDYrXiL1TO8pxV4UaB56NgTxPfOMKBPJqeYvumEZ3aNrcsd1N6zXZhzZ+NtoTAFPVSrspalY=
  on:
    tags: true
    node: 8
